{% set version = "2023.12.1+402" %}
{% set pkg_version = version.split("+")[0] %}
# reset the below to 0 when bumping upstream build num.
{% set build = 2 %}
{% set upstream_build_num = version.split("+")[1] | int %}

package:
  name: rstudio-desktop
  version: {{ pkg_version }}

source:
  url: https://github.com/rstudio/rstudio/archive/refs/tags/{{ version }}.tar.gz
  sha256: 196d31094d580a74737fbf689d2d0b302da5fec13694aa1d63f8875d3e45e4dd
  patches:
    - patches/0001-boost-static-libs.patch

build:
  number: {{ upstream_build_num + build }}
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/rstudio/lib
    - lib/

build:
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/rstudio/lib
    - lib/

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - cmake
    - ant
    - yarn
    - wget
    - ripgrep
    - coreutils  # [osx]
    - patchelf  # [linux]
    - unzip
    - nodejs >=18
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
  host:
    - r-base
    - r-purrr
    - r-rmarkdown
    - r-renv
    - r-testthat
    - r-xml2
    - r-yaml
    - r-rstudioapi
    - libxkbcommon  # [linux]
    - xorg-libxcomposite  # [linux]
    - xorg-libxcursor  # [linux]
    - xorg-libxscrnsaver  # [linux]
    - xorg-libxi  # [linux]
    - xorg-libxtst  # [linux]
    - xorg-libxrandr  # [linux]
    - openjdk
    - libboost-devel
    - soci-postgresql
    - soci-core
    - soci-sqlite
    - libpq
    - qt-main
    - qt-webengine
    - libuuid  # [linux]
    - bzip2
    - zlib
    - pango
    - sqlite
    - libcups  # [linux]
    - openssl
    - hunspell
    - hunspell-en
    - pandoc
    - mathjax <3.0
    - yaml-cpp <0.7
    - libjpeg-turbo   # [osx]
    - libpng  # [osx]
    - quarto
  run:
    - r-base
    - r-purrr
    - r-rmarkdown
    - r-renv
    - r-testthat
    - r-xml2
    - r-yaml
    - r-rstudioapi
    - libxkbcommon  # [linux]
    - libxkbcommon  # [linux]
    - xorg-libxcomposite  # [linux]
    - xorg-libxcursor  # [linux]
    - xorg-libxscrnsaver  # [linux]
    - xorg-libxi  # [linux]
    - xorg-libxtst  # [linux]
    - xorg-libxrandr  # [linux]
    - openjdk
    - soci-postgresql
    - soci-core
    - soci-sqlite
    - libpq
    - qt-main
    - qt-webengine
    - libuuid  # [linux]
    - bzip2
    - zlib
    - pango
    - sqlite
    - libcups  # [linux]
    - openssl
    - hunspell
    - hunspell-en
    - pandoc
    - mathjax <3.0
    - yaml-cpp <0.7
    - libjpeg-turbo   # [osx]
    - libpng  # [osx]
    - {{ pin_compatible("quarto", max_pin="x.x") }}
test:
  commands:
    - test -f ${PREFIX}/lib/rstudio/bin/rstudio  # [linux]
    - sh -c "xvfb-run -s '-screen 0 1200x800x24' ${PREFIX}/bin/rstudio --no-sandbox --run-diagnostics; cat ~/rstudio-diagnostics/diagnostics-report.txt"  # [linux]
    - test -f ${PREFIX}/lib/rstudio/RStudio.app/Contents/MacOS/RStudio  # [osx]

about:
  home: https://www.rstudio.com/
  license: AGPL-3.0-only
  license_family: GPL
  license_file: COPYING
  summary: RStudio is an integrated development environment (IDE) for R
  description: |
    RStudio is an integrated development environment (IDE)
    for R. It includes a console, syntax-highlighting
    editor that supports direct code execution, as well
    as tools for plotting, history, debugging and
    workspace management.
  doc_url: https://support.rstudio.com/hc/en-us/sections/200107586-Using-RStudio
  dev_url: https://github.com/rstudio/rstudio


extra:
  recipe-maintainers:
    - izahn
    - h-vetinari
    - wolfv
  feedstock-name: rstudio
