{% set version = "2022.12.0+353" %}
{% set pkg_version = version.split("+")[0] %}
# reset the below to 0 when bumping upstream build num.
{% set build = 0 %}
{% set upstream_build_num = version.split("+")[1] | int %}


package:
  name: rstudio
  version: {{ pkg_version }}

source:
  url: https://github.com/rstudio/rstudio/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e4f3503e2ad4229301360f56fd5288e5c8e769c490073dae7fe40366237ecce0
  patches:
    - 0001-fix-soci.patch
    - 0002-no-static-linking.patch

build:
  number: {{ upstream_build_num + build }}
  skip: true  # [win]
  # nodejs 14 is not co-installable with openssl 3;
  # also, upstream moved to 16 already
  skip: true  # [nodejs == 14]
  rpaths:
    - lib/R/lib/
    - lib/rstudio/lib
    - lib/

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - cmake
    - ant
    - yarn
    - wget
    - ripgrep
    - coreutils  # [osx]
    - patchelf  # [linux]
    - unzip
    - nodejs
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]

outputs:
  - name: rstudio-desktop
    script: build-desktop.sh
    build:
      skip: true  # [win]
      skip: true  # [nodejs == 14]
      rpaths:
        - lib/R/lib/
        - lib/rstudio/lib
        - lib/
    requirements:
      build:
        - {{ compiler('cxx') }}
        - make
        - cmake
        - ant
        - yarn
        - wget
        - ripgrep
        - coreutils  # [osx]
        - patchelf  # [linux]
        - unzip
        - nodejs
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('mesa-dri-drivers') }}  # [linux]
        - {{ cdt('libselinux') }}  # [linux]
        - {{ cdt('libxdamage') }}  # [linux]
        - {{ cdt('libxxf86vm') }}  # [linux]
        - {{ cdt('libxext') }}     # [linux]
      host:
        - r-base
        - r-purrr
        - r-rmarkdown
        - r-renv
        - r-testthat
        - r-xml2
        - r-yaml
        - r-rstudioapi
        - libxkbcommon  # [linux]
        - xorg-libxcomposite  # [linux]
        - xorg-libxcursor  # [linux]
        - xorg-libxscrnsaver  # [linux]
        - xorg-libxi  # [linux]
        - xorg-libxtst  # [linux]
        - xorg-libxrandr  # [linux]
        - openjdk
        - boost-cpp
        - soci-postgresql
        - soci-core
        - soci-sqlite
        - libpq
        - qt-main
        - qt-webengine
        - libuuid  # [linux]
        - bzip2
        - zlib
        - pango
        - sqlite
        - libcups  # [linux]
        - openssl
        - hunspell
        - hunspell-en
        - pandoc
        - mathjax <3.0
        - yaml-cpp <0.7
        - jpeg  # [osx]
        - libpng  # [osx]
        - quarto
      run:
        - r-base
        - r-purrr
        - r-rmarkdown
        - r-renv
        - r-testthat
        - r-xml2
        - r-yaml
        - r-rstudioapi
        - libxkbcommon  # [linux]
        - libxkbcommon  # [linux]
        - xorg-libxcomposite  # [linux]
        - xorg-libxcursor  # [linux]
        - xorg-libxscrnsaver  # [linux]
        - xorg-libxi  # [linux]
        - xorg-libxtst  # [linux]
        - xorg-libxrandr  # [linux]
        - openjdk
        - boost-cpp
        - soci-postgresql
        - soci-core
        - soci-sqlite
        - libpq
        - qt-main
        - qt-webengine
        - libuuid  # [linux]
        - bzip2
        - zlib
        - pango
        - sqlite
        - libcups  # [linux]
        - openssl
        - hunspell
        - hunspell-en
        - pandoc
        - mathjax <3.0
        - yaml-cpp <0.7
        - jpeg  # [osx]
        - libpng  # [osx]
        - {{ pin_compatible("quarto", max_pin="x.x") }}
    test:
      commands:
        - test -f ${PREFIX}/lib/rstudio/bin/rstudio  # [linux]
        - sh -c "xvfb-run -s '-screen 0 1200x800x24' ${PREFIX}/bin/rstudio --no-sandbox --run-diagnostics; cat ~/rstudio-diagnostics/diagnostics-report.txt"  # [linux]
        - test -f ${PREFIX}/lib/rstudio/RStudio.app/Contents/MacOS/RStudio  # [osx]

about:
  home: https://www.rstudio.com/
  license: AGPL-3.0-only
  license_family: GPL
  license_file: COPYING
  summary: RStudio is an integrated development environment (IDE) for R
  description: |
    RStudio is an integrated development environment (IDE)
    for R. It includes a console, syntax-highlighting
    editor that supports direct code execution, as well
    as tools for plotting, history, debugging and
    workspace management.
  doc_url: https://support.rstudio.com/hc/en-us/sections/200107586-Using-RStudio
  dev_url: https://github.com/rstudio/rstudio


extra:
  recipe-maintainers:
    - izahn
    - h-vetinari
  feedstock-name: rstudio
